FROM node:20-alpine

WORKDIR /usr/app

COPY package.json ./

RUN npm install

COPY . .

ARG NEXT_PUBLIC_DOMAIN
ARG NEXT_PUBLIC_SERVICES_BASE_URL

ENV NEXT_PUBLIC_DOMAIN=$NEXT_PUBLIC_DOMAIN
ENV NEXT_PUBLIC_SERVICES_BASE_URL=$NEXT_PUBLIC_SERVICES_BASE_URL

RUN echo "NEXT_PUBLIC_DOMAIN=$NEXT_PUBLIC_DOMAIN" >> .env
RUN echo "NEXT_PUBLIC_SERVICES_BASE_URL=$NEXT_PUBLIC_SERVICES_BASE_URL" >> .env

RUN npm i -g pnpm

RUN pnpm build  

EXPOSE 3000 

CMD ["pnpm", "start"]
